// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhI5mE8Sv_7zVpeWDJ2_K62f1kniepReU',
    appId: '1:587516242316:web:9f4819dd78b12afa1ecea9',
    messagingSenderId: '587516242316',
    projectId: 'to-do-list-ee163',
    authDomain: 'to-do-list-ee163.firebaseapp.com',
    storageBucket: 'to-do-list-ee163.appspot.com',
    measurementId: 'G-D9NBM5RBQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBkuZE172ZmYgICFzzR_Megqo2KxI5xwI',
    appId: '1:587516242316:android:9812d303c03e81371ecea9',
    messagingSenderId: '587516242316',
    projectId: 'to-do-list-ee163',
    storageBucket: 'to-do-list-ee163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1D23xTACCD5r_ih91b_ZTHArv9-4GSM',
    appId: '1:587516242316:ios:30a865fe28aa27081ecea9',
    messagingSenderId: '587516242316',
    projectId: 'to-do-list-ee163',
    storageBucket: 'to-do-list-ee163.appspot.com',
    iosClientId: '587516242316-v8q8c4lgk7u5kcfg0ddjrmlft20goag6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1D23xTACCD5r_ih91b_ZTHArv9-4GSM',
    appId: '1:587516242316:ios:d6437950e3cd3e541ecea9',
    messagingSenderId: '587516242316',
    projectId: 'to-do-list-ee163',
    storageBucket: 'to-do-list-ee163.appspot.com',
    iosClientId: '587516242316-3v7p3h21723r8oum8aipp3ke8t9jedqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
